import React from 'react';
import {
  BookOpen,
  Download,
  FileSpreadsheet,
  Plus,
  Upload,
  AlertTriangle,
  CheckCircle2,
  Info,
  GraduationCap,
  ListChecks,
  HelpCircle,
  Wrench,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { LOGICAL_MODULES, WORKSHOP_MODULES } from '../data/masterCatalogue';
import {
  buildMasterWorkbook,
  downloadWorkbook,
  DEALER_TARGETS,
  FIELD_TYPES,
  PROTECTED_MASTER_IDS,
} from '../utils/masterWorkbook';

/** Static copies served with the app (generated by `npm run templates`). */
const downloadUrl = (file: string) => `${import.meta.env.BASE_URL}downloads/${file}`;

const FILES = [
  {
    file: 'TML_Master_Definition_Template.xlsx',
    title: 'Blank Template',
    desc: 'Start here. README sheet + one worked example (Tyre Brand Master) to copy.',
    icon: FileSpreadsheet,
  },
  {
    file: 'TML_Master_Practice_Workbook.xlsx',
    title: 'Practice Workbook',
    desc: 'Ready-made file to rehearse: creates a new master and adds a missed field to an existing one.',
    icon: GraduationCap,
  },
  {
    file: 'TML_Existing_Masters_Catalogue.xlsx',
    title: 'Existing Masters Catalogue',
    desc: 'Every master shipped with the system, in the same format — check here before creating one.',
    icon: ListChecks,
  },
];

const Section: React.FC<{ id: string; title: string; icon: React.ElementType; children: React.ReactNode }> = ({
  id,
  title,
  icon: Icon,
  children,
}) => (
  <section id={id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-2xs space-y-3 scroll-mt-4">
    <h2 className="text-sm font-extrabold text-slate-900 flex items-center gap-2">
      <Icon className="h-4 w-4 text-blue-700" /> {title}
    </h2>
    <div className="text-xs text-slate-700 space-y-2 leading-relaxed">{children}</div>
  </section>
);

const Steps: React.FC<{ items: React.ReactNode[] }> = ({ items }) => (
  <ol className="space-y-1.5">
    {items.map((item, i) => (
      <li key={i} className="flex gap-2">
        <span className="h-5 w-5 shrink-0 rounded-full bg-blue-900 text-white text-[10px] font-bold flex items-center justify-center">
          {i + 1}
        </span>
        <span className="pt-0.5">{item}</span>
      </li>
    ))}
  </ol>
);

const Table: React.FC<{ head: string[]; rows: React.ReactNode[][]; prose?: boolean }> = ({ head, rows, prose }) => (
  <div className="overflow-x-auto rounded-xl border border-slate-200">
    <table className="w-full text-left text-[11px]">
      <thead className="bg-slate-50 text-slate-500 uppercase tracking-wider">
        <tr>
          {head.map((h) => (
            <th key={h} className="px-3 py-2 font-semibold">{h}</th>
          ))}
        </tr>
      </thead>
      <tbody className="divide-y divide-slate-100">
        {rows.map((r, i) => (
          <tr key={i} className="align-top">
            {r.map((c, j) => (
              <td key={j} className={`px-3 py-1.5 ${j === 0 ? (prose ? 'font-semibold text-slate-900' : 'font-mono font-semibold text-slate-900 whitespace-nowrap') : ''}`}>
                {c}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

const Code: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <code className="px-1 py-0.5 rounded bg-slate-100 border border-slate-200 font-mono text-[11px] text-slate-800">{children}</code>
);

const TOC = [
  ['before', 'Before you start'],
  ['downloads', 'Downloads'],
  ['choose', 'Which option to use'],
  ['create', 'A. Create one master (form)'],
  ['workbook', 'B. Prepare a workbook'],
  ['import', 'C. Import the workbook'],
  ['missed', 'D. Add something you missed later'],
  ['practice', '10-minute practice'],
  ['errors', 'Fixing errors'],
  ['verify', 'Check the result'],
  ['faq', 'FAQ'],
  ['reference', 'Allowed values'],
];

export const MasterGuidePage: React.FC = () => {
  const { navigate, masterConfigs, showToast } = useApp();

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="rounded-2xl bg-[#002B49] text-white p-5 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="text-[11px] font-bold uppercase tracking-wider text-blue-200">Masters Maintenance · BA Guide</div>
          <h1 className="text-xl font-black tracking-tight mt-0.5 flex items-center gap-2">
            <BookOpen className="h-5 w-5" /> Adding Masters Without a Deployment
          </h1>
          <p className="text-xs text-blue-100 mt-1 max-w-2xl">
            Everything you need to define new masters, or add fields and values that were missed, directly in the portal.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => navigate('/admin/masters?open=create')}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-white text-blue-950 text-xs font-bold hover:bg-blue-50 cursor-pointer"
          >
            <Plus className="h-3.5 w-3.5" /> Open Create New Master
          </button>
          <button
            onClick={() => navigate('/admin/masters?open=import')}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-indigo-500 text-white text-xs font-bold hover:bg-indigo-400 cursor-pointer"
          >
            <Upload className="h-3.5 w-3.5" /> Open Import BA Workbook
          </button>
        </div>
      </div>

      {/* Table of contents */}
      <nav aria-label="Guide contents" className="flex flex-wrap gap-1.5 text-[11px]">
        {TOC.map(([id, label]) => (
          <button
            key={id}
            onClick={() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })}
            className="px-2.5 py-1 rounded-full border border-slate-200 bg-white text-slate-700 hover:border-blue-400 hover:text-blue-800 cursor-pointer"
          >
            {label}
          </button>
        ))}
      </nav>

      <Section id="before" title="Before you start" icon={Info}>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use <strong>Chrome or Edge</strong> on a laptop.</li>
          <li>
            Keep the <strong>Role View</strong> (top bar) on <em>Super Administrator</em>. In Masters Maintenance keep the toggle on{' '}
            <strong>TML Admin</strong> — workbook import is only available there.
          </li>
          <li className="text-amber-800">
            <strong>This is a prototype.</strong> What you create is saved <strong>only in your own browser</strong>; colleagues won't see it.
            The site is publicly reachable — <strong>use test data only</strong>, nothing confidential.
          </li>
          <li>
            To start over with a clean slate, clear this site's data in your browser (Settings → Privacy → Site data).
          </li>
        </ul>
      </Section>

      <Section id="downloads" title="Downloads" icon={Download}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {FILES.map(({ file, title, desc, icon: Icon }) => (
            <a
              key={file}
              href={downloadUrl(file)}
              download={file}
              className="group rounded-xl border border-slate-200 p-3.5 hover:border-blue-400 hover:bg-blue-50/40 transition-colors flex flex-col gap-1.5"
            >
              <span className="flex items-center gap-2 font-bold text-slate-900">
                <Icon className="h-4 w-4 text-emerald-600" /> {title}
              </span>
              <span className="text-[11px] text-slate-500 flex-1">{desc}</span>
              <span className="text-[11px] font-bold text-blue-700 flex items-center gap-1 group-hover:underline">
                <Download className="h-3 w-3" /> {file}
              </span>
            </a>
          ))}
        </div>
        <button
          onClick={() => {
            const exportable = masterConfigs.filter((m) => !PROTECTED_MASTER_IDS.includes(m.id));
            downloadWorkbook(buildMasterWorkbook(exportable), `TML_My_Masters_${new Date().toISOString().slice(0, 10)}.xlsx`);
            showToast(`Exported ${exportable.length} masters (including ones you created)`, 'success');
          }}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-300 bg-white font-semibold hover:bg-slate-50 cursor-pointer"
        >
          <FileSpreadsheet className="h-3.5 w-3.5 text-emerald-600" /> Export my current masters (includes what I created)
        </button>
      </Section>

      <Section id="choose" title="Which option to use" icon={ListChecks}>
        <Table
          prose
          head={['You have…', 'Use']}
          rows={[
            ['One new master', <>Path <strong>A</strong> — Create New Master form</>],
            ["A module's masters in Excel", <>Paths <strong>B + C</strong> — workbook import</>],
            ['A field or values missed in an existing master', <>Path <strong>D</strong> — workbook with "Update existing masters", or <em>+ Add Custom Parameter</em> on that master</>],
            ['Just a few rows for an existing master', <>Open the master → <em>+ Add Row</em> or <em>⬆ Bulk Upload</em></>],
          ]}
        />
      </Section>

      <Section id="create" title="A. Create one master with the form" icon={Plus}>
        <Steps
          items={[
            <>Go to <strong>Administration → Masters Maintenance</strong> and click <strong>Create New Master</strong>.</>,
            <>Type the <strong>Master Name</strong>. The <strong>Master ID</strong> fills in automatically (e.g. <Code>tyre_brand_master</Code>) — keep it unless you need a specific ID.</>,
            <>Choose the <strong>Logical Group</strong>, <strong>Service Module</strong> and <strong>Governance Owner</strong> (TML Central = OEM-controlled; Dealership Floor = dealers can edit).</>,
            <>Add the fields: label, type, <em>Req.</em> for mandatory, dropdown options (comma separated), and tick <strong>Show in Dealer App</strong> if dealers should see it.</>,
            <>Click <strong>Create Master</strong>. It opens straight away — add rows with <strong>+ Add Row</strong>, or ranges / value mappings with <strong>+ Add Custom Parameter</strong>.</>,
          ]}
        />
      </Section>

      <Section id="workbook" title="B. Prepare a workbook" icon={FileSpreadsheet}>
        <p>
          Start from the <strong>Blank Template</strong>. One workbook can hold many masters. It has three kinds of sheets
          (the README sheet is ignored on import):
        </p>
        <p className="font-bold text-slate-900 pt-1">1. "Masters" sheet — one row per master</p>
        <Table
          head={['Column', 'What to enter', 'Example']}
          rows={[
            ['Master ID', 'lowercase letters, digits, _ · 3–31 chars · unique · also the name of its records sheet', <Code>tyre_brand_master</Code>],
            ['Master Name', 'Name shown in the portal', 'Tyre Brand Master'],
            ['Module Code', 'Service module (see Allowed values)', <Code>bodyshop</Code>],
            ['Logical Group', 'Portal tab it appears under (see Allowed values)', 'Parts, Claims & Support'],
            ['Owner', <><Code>TML_ADMIN</Code> or <Code>DEALER_ADMIN</Code></>, 'TML_ADMIN'],
            ['Category / Description', 'Free text', 'Tyres & Wheels'],
          ]}
        />
        <p className="font-bold text-slate-900 pt-1">2. "Fields" sheet — one row per field</p>
        <Table
          head={['Column', 'What to enter', 'Example']}
          rows={[
            ['Master ID', 'Which master the field belongs to', <Code>tyre_brand_master</Code>],
            ['Field Key', <>Like <Code>brand_name</Code>; blank = made from the label; <Code>id</Code> is reserved</>, <Code>warranty_months</Code>],
            ['Field Label', 'Shown to users', 'Warranty (Months)'],
            ['Type', FIELD_TYPES.join(' · ') + ' (select = dropdown)', 'number'],
            ['Mandatory', 'Y / N', 'Y'],
            ['Options', 'Dropdown values, comma separated, at least 2', 'PV, EV, CV'],
            ['Min / Max', 'Number limits', '0 / 120'],
            ['Min Date / Max Date', 'YYYY-MM-DD', '2026-04-01'],
            ['Pattern + Pattern Error Message', 'Optional format rule for text, and the message users see', <Code>^[A-Z]{'{3}'}$</Code>],
            ['Show in Dealer App', 'Y / N', 'Y'],
            ['Dealer Target Module', 'Dealer screen (see Allowed values)', 'job_card'],
            ['Dealer Label', 'Optional label dealers see', 'Vehicle Segment'],
            ['Value Mapping', 'CODE=Dealer text; CODE2=Other text', 'PV=Passenger Vehicle; EV=Electric Vehicle'],
          ]}
        />
        <p className="font-bold text-slate-900 pt-1">3. One records sheet per master</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>The sheet name must be <strong>exactly the Master ID</strong>.</li>
          <li>Row 1 = <Code>id</Code> plus one column per field (field key or field label both work).</li>
          <li><Code>id</Code> is optional — blank ids are generated. Booleans: <Code>Y</Code>/<Code>N</Code>. Dates: <Code>YYYY-MM-DD</Code>.</li>
        </ul>
      </Section>

      <Section id="import" title="C. Import the workbook" icon={Upload}>
        <Steps
          items={[
            <>Masters Maintenance → <strong>Import BA Workbook</strong>.</>,
            <>Upload your <strong>.xlsx</strong> file.</>,
            <>Choose what happens if a master already exists: <strong>Skip it</strong> (safe for first loads) or <strong>Update existing masters</strong> (see D).</>,
            <>Review the table: <span className="text-emerald-700 font-bold">NEW</span>, <span className="text-blue-700 font-bold">UPDATE</span> or <span className="text-slate-500 font-bold">SKIPPED</span> per master.</>,
            <>If errors are listed, fix them in Excel (each shows the <strong>sheet and row</strong>) and upload again. Nothing is imported while errors exist.</>,
            <>Click <strong>Import</strong>. The first imported master opens automatically. The change is recorded in the Audit Log.</>,
          ]}
        />
      </Section>

      <Section id="missed" title="D. Add something you missed later" icon={Wrench}>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            Put the existing master's row in the <strong>Masters</strong> sheet (copy it from the Existing Masters Catalogue), add only the{' '}
            <strong>new field(s)</strong> in the Fields sheet, and in its records sheet include <Code>id</Code> + the new column.
          </li>
          <li>Import with <strong>Update existing masters</strong> selected.</li>
          <li>
            Existing fields are <strong>never changed or removed</strong> by an import. Rows are matched by <Code>id</Code>: existing ids are updated,
            new ids are added. <strong>Blank cells on existing rows are left unchanged.</strong>
          </li>
          <li>To change or remove an existing field, do it in that master's table so it's deliberate and audited.</li>
        </ul>
      </Section>

      <Section id="practice" title="10-minute practice" icon={GraduationCap}>
        <Steps
          items={[
            <>Download the <strong>Practice Workbook</strong> (Downloads above) and open it in Excel to see how it's filled.</>,
            <>Open <strong>Import BA Workbook</strong>, upload it with <strong>Skip it</strong> selected: <em>Courtesy Car Master</em> shows NEW and the PPL master shows SKIPPED.</>,
            <>Switch to <strong>Update existing masters</strong>: the PPL master changes to UPDATE (+1 new field). Click <strong>Import 2 Master(s)</strong>.</>,
            <>Check: <em>Courtesy Car Master</em> (Service Operations tab) has 3 rows; <em>PPL &amp; PL Master</em> (Vehicle Data tab) has a new <strong>ADAS Level</strong> column filled for PPL-01 and PPL-02.</>,
            <>Now break it on purpose: in Excel set a <em>Max Days</em> value to <Code>30</Code> or a <em>Fuel</em> to <Code>Hydrogen</Code>, upload again and read the error messages.</>,
          ]}
        />
      </Section>

      <Section id="errors" title="Fixing errors" icon={AlertTriangle}>
        <Table
          prose
          head={['Message says…', 'What to do']}
          rows={[
            ['Sheet "Masters" / "Fields" is missing', 'Keep the sheet names exactly as in the template.'],
            ['Master ID … must be 3–31 characters', 'Use lowercase letters, digits and underscores only, e.g. paint_code_master.'],
            ['… already exists and was skipped', 'Normal for existing masters. Choose "Update existing masters" if you meant to add to it.'],
            ['Module code / Logical group / Owner is not valid', 'Copy the exact value from Allowed values below.'],
            ['dropdown fields need at least 2 options', 'List 2+ comma-separated values in Options.'],
            ['"X" is not a valid option for …', 'The record value must be one of that field\'s Options (spelling and case must match).'],
            ['… is required', 'A mandatory field is empty in that row.'],
            ['must be a valid numeric value / cannot be greater than …', 'Fix the number or the field\'s Min/Max.'],
            ['must be in valid YYYY-MM-DD format', 'Format the cell as text, e.g. 2026-09-30.'],
            ['Record id "…" appears more than once', 'Each row in a records sheet needs a unique id.'],
            ['Fields reference "…" which is not listed', 'Add that master to the Masters sheet, or fix the Master ID spelling.'],
            ['Column "…" doesn\'t match any field (warning)', 'The column header isn\'t a field key/label of that master — it is ignored.'],
          ]}
        />
      </Section>

      <Section id="verify" title="Check the result" icon={CheckCircle2}>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Masters Maintenance</strong> → the master's group tab → its tab in the workspace: fields as columns, records as rows.</li>
          <li>Try <strong>+ Add Row</strong> with a wrong value to see the validation you defined.</li>
          <li>
            Fields with <em>Show in Dealer App</em> + target <Code>vehicle_journey</Code> or <Code>general</Code> appear on{' '}
            <button className="text-blue-700 font-semibold underline cursor-pointer" onClick={() => navigate('/journey/JC20260930001234')}>
              Vehicle Journey
            </button>{' '}
            in the "Configured Master Extended Attributes" card.
          </li>
          <li>
            Every create/import is listed in the{' '}
            <button className="text-blue-700 font-semibold underline cursor-pointer" onClick={() => navigate('/admin/audit')}>
              Audit Log
            </button>{' '}
            and the Masters <em>Change Log</em> tab.
          </li>
        </ul>
      </Section>

      <Section id="faq" title="FAQ" icon={HelpCircle}>
        <dl className="space-y-2">
          {[
            ['Will my colleagues see what I import?', 'No. In this prototype everything stays in your own browser. Share your Excel file instead.'],
            ['Can I import the same file twice?', 'Yes. With "Skip it" existing masters are skipped; with "Update" rows are matched by id, so nothing is duplicated.'],
            ['Can an import delete anything?', 'No. Imports only add masters, add fields and add/update rows.'],
            ['Why is "Import BA Workbook" refused?', 'Switch the toggle in Masters Maintenance to TML Admin.'],
            ['Bay Management / Holiday Calendar / Time Slots / Dealer Registry?', 'These have their own screens and cannot be changed by import.'],
          ].map(([q, a]) => (
            <div key={q}>
              <dt className="font-bold text-slate-900">{q}</dt>
              <dd className="text-slate-600">{a}</dd>
            </div>
          ))}
        </dl>
      </Section>

      <Section id="reference" title="Allowed values" icon={ListChecks}>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Table head={['Module Code', 'Module']} rows={WORKSHOP_MODULES.map((m) => [m.code, m.title])} />
          <div className="space-y-4">
            <Table head={['Logical Group', 'Portal tab']} rows={LOGICAL_MODULES.map((g) => [g.id, g.title])} />
            <Table head={['Owner', 'Meaning']} rows={[['TML_ADMIN', 'OEM-governed (TML Central)'], ['DEALER_ADMIN', 'Dealer-editable']]} />
            <Table head={['Dealer Target Module', '']} rows={DEALER_TARGETS.map((t) => [t, ''])} />
            <Table head={['Type', '']} rows={FIELD_TYPES.map((t) => [t, t === 'select' ? 'dropdown' : t === 'boolean' ? 'Y/N' : ''])} />
          </div>
        </div>
      </Section>
    </div>
  );
};
