/**
 * masterExportUtil.ts
 * Enterprise utility for exporting master data to CSV and Microsoft Excel (.xls/.xlsx compatible format)
 * with UTF-8 BOM, metadata banners, and styling for reporting and audit compliance.
 */

export interface ExportColumnDef {
  key: string;
  label: string;
}

export interface MasterExportOptions {
  masterName: string;
  category?: string;
  buFilter?: string;
  currentUser?: { userId: string; name: string };
  columns: ExportColumnDef[];
  data: Array<Record<string, any>>;
}

export interface ModuleMasterItem {
  masterName: string;
  moduleName: string;
  category: string;
  owner: string;
  description: string;
  recordCount: number;
  fieldsCount: number;
  records: Array<Record<string, any>>;
  fields: Array<{ key: string; label: string }>;
}

export const masterExportUtil = {
  /**
   * Export to CSV with UTF-8 BOM for flawless Excel encoding and special character support
   */
  exportToCSV: (options: MasterExportOptions) => {
    const { masterName, category, currentUser, columns, data } = options;
    const now = new Date();
    const timestampStr = now.toISOString().slice(0, 10);
    const timeFormatted = now.toLocaleString('en-IN');

    // Report Metadata Header rows for reporting compliance
    const metaHeader = [
      `"Report Title","Tata Motors Service Transformation — ${masterName.replace(/"/g, '""')}"`,
      `"Module / Category","${(category || 'Enterprise Masters').replace(/"/g, '""')}"`,
      `"Generated By","${(currentUser ? `${currentUser.name} (${currentUser.userId})` : 'System Administrator').replace(/"/g, '""')}"`,
      `"Generated At","${timeFormatted.replace(/"/g, '""')}"`,
      `"Total Records","${data.length}"`,
      `""`, // Blank separator row
    ].join('\r\n');

    const headers = columns.map((col) => `"${col.label.replace(/"/g, '""')}"`).join(',');
    const rows = data.map((row) =>
      columns
        .map((col) => {
          const val = row[col.key];
          if (val === undefined || val === null) return '""';
          if (Array.isArray(val)) return `"${val.join('; ').replace(/"/g, '""')}"`;
          return `"${String(val).replace(/"/g, '""')}"`;
        })
        .join(',')
    );

    // UTF-8 BOM prefix (\uFEFF) ensures Excel & CSV readers open text correctly
    const csvContent = '\uFEFF' + metaHeader + '\r\n' + [headers, ...rows].join('\r\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    const cleanName = masterName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.setAttribute('href', url);
    link.setAttribute('download', `TML_${cleanName}_report_${timestampStr}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Export entire logical module masters to a consolidated CSV for reporting
   */
  exportModuleToCSV: (
    moduleTitle: string,
    masters: ModuleMasterItem[],
    currentUser?: { userId: string; name: string }
  ) => {
    const now = new Date();
    const timestampStr = now.toISOString().slice(0, 10);
    const timeFormatted = now.toLocaleString('en-IN');

    const totalRecords = masters.reduce((acc, m) => acc + m.recordCount, 0);

    // Meta Header for reporting
    let csvContent = '\uFEFF';
    csvContent += `"TATA MOTORS SERVICE TRANSFORMATION — MASTER DATA MODULE REPORT"\r\n`;
    csvContent += `"Module Name","${moduleTitle.replace(/"/g, '""')}"\r\n`;
    csvContent += `"Generated By","${(currentUser ? `${currentUser.name} (${currentUser.userId})` : 'Administrator').replace(/"/g, '""')}"\r\n`;
    csvContent += `"Generated At","${timeFormatted}"\r\n`;
    csvContent += `"Total Masters Included","${masters.length}"\r\n`;
    csvContent += `"Total Configured Records","${totalRecords}"\r\n`;
    csvContent += `\r\n`;

    // Section 1: Summary Table of Masters
    csvContent += `"--- MODULE MASTERS EXECUTIVE SUMMARY ---"\r\n`;
    csvContent += `"Master Name","Category","Governance Authority","Field Columns","Records","Scope Description"\r\n`;
    masters.forEach((m) => {
      csvContent += `"${m.masterName.replace(/"/g, '""')}","${m.category.replace(/"/g, '""')}","${m.owner.replace(/"/g, '""')}","${m.fieldsCount}","${m.recordCount}","${m.description.replace(/"/g, '""')}"\r\n`;
    });
    csvContent += `\r\n`;

    // Section 2: Detailed Data Records for Each Master
    csvContent += `"--- DETAILED MASTER RECORDS DATA ---"\r\n`;
    masters.forEach((m) => {
      csvContent += `\r\n"### MASTER: ${m.masterName.replace(/"/g, '""')} (${m.category} - ${m.owner}) ###"\r\n`;
      if (m.fields.length > 0 && m.records.length > 0) {
        const headers = m.fields.map((f) => `"${f.label.replace(/"/g, '""')}"`).join(',');
        csvContent += headers + '\r\n';
        m.records.forEach((row) => {
          const rowText = m.fields
            .map((f) => {
              const val = row[f.key];
              if (val === undefined || val === null) return '""';
              if (Array.isArray(val)) return `"${val.join('; ').replace(/"/g, '""')}"`;
              return `"${String(val).replace(/"/g, '""')}"`;
            })
            .join(',');
          csvContent += rowText + '\r\n';
        });
      } else {
        csvContent += `"No tabular data records configured."\r\n`;
      }
    });

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    const cleanName = moduleTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.setAttribute('href', url);
    link.setAttribute('download', `TML_${cleanName}_module_report_${timestampStr}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Export to styled Excel spreadsheet (.xls / HTML Table format compliant with Excel)
   */
  exportToExcel: (options: MasterExportOptions) => {
    const { masterName, category, buFilter, currentUser, columns, data } = options;
    const now = new Date();
    const timestampStr = now.toISOString().slice(0, 10);
    const timeFormatted = now.toLocaleString('en-IN');

    const headerCells = columns
      .map(
        (col) =>
          `<th style="background-color: #002B49; color: #FFFFFF; font-weight: bold; padding: 10px; border: 1px solid #CBD5E1; text-align: left;">${col.label}</th>`
      )
      .join('');

    const dataRows = data
      .map((row, idx) => {
        const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
        const cells = columns
          .map((col) => {
            const val = row[col.key];
            const text = val !== undefined && val !== null ? (Array.isArray(val) ? val.join(', ') : String(val)) : '';
            return `<td style="padding: 8px; border: 1px solid #E2E8F0; background-color: ${bg};">${text}</td>`;
          })
          .join('');
        return `<tr>${cells}</tr>`;
      })
      .join('');

    const excelHtml = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <!--[if gte mso 9]>
        <xml>
          <x:ExcelWorkbook>
            <x:ExcelWorksheets>
              <x:ExcelWorksheet>
                <x:Name>${masterName.slice(0, 31)}</x:Name>
                <x:WorksheetOptions>
                  <x:DisplayGridlines/>
                </x:WorksheetOptions>
              </x:ExcelWorksheet>
            </x:ExcelWorksheets>
          </x:ExcelWorkbook>
        </xml>
        <![endif]-->
        <meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">
      </head>
      <body>
        <table style="font-family: Calibri, Arial, sans-serif; font-size: 11pt; border-collapse: collapse;">
          <tr>
            <td colspan="${columns.length}" style="font-size: 16pt; font-weight: bold; color: #002B49; padding: 12px 0;">
              Tata Motors Service Transformation — ${masterName}
            </td>
          </tr>
          <tr>
            <td colspan="${columns.length}" style="color: #64748B; font-size: 10pt; padding-bottom: 8px;">
              Category: <b>${category || 'Enterprise Masters'}</b> | BU Filter: <b>${buFilter || 'All'}</b> | Generated by: <b>${currentUser ? `${currentUser.name} (${currentUser.userId})` : 'System Administrator'}</b> | Generated on: <b>${timeFormatted}</b> | Records: <b>${data.length}</b>
            </td>
          </tr>
          <thead>
            <tr>${headerCells}</tr>
          </thead>
          <tbody>
            ${dataRows}
          </tbody>
        </table>
      </body>
      </html>
    `;

    const blob = new Blob([excelHtml], { type: 'application/vnd.ms-excel;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    const cleanName = masterName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.setAttribute('href', url);
    link.setAttribute('download', `TML_${cleanName}_export_${timestampStr}.xls`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },
};
