/**
 * masterExportUtil.ts
 * Enterprise utility for exporting master data to CSV and Microsoft Excel (.xls/.xlsx compatible format)
 * with UTF-8 BOM, metadata banners, and styling.
 */

export interface ExportColumnDef {
  key: string;
  label: string;
}

export interface MasterExportOptions {
  masterName: string;
  category?: string;
  buFilter?: string;
  currentUser?: { userId: string; name: string };
  columns: ExportColumnDef[];
  data: Array<Record<string, any>>;
}

export const masterExportUtil = {
  /**
   * Export to CSV with UTF-8 BOM for flawless Excel encoding
   */
  exportToCSV: (options: MasterExportOptions) => {
    const { masterName, columns, data } = options;
    const now = new Date();
    const timestampStr = now.toISOString().slice(0, 10);

    const headers = columns.map((col) => `"${col.label.replace(/"/g, '""')}"`).join(',');
    const rows = data.map((row) =>
      columns
        .map((col) => {
          const val = row[col.key];
          const text = val !== undefined && val !== null ? String(val) : '';
          return `"${text.replace(/"/g, '""')}"`;
        })
        .join(',')
    );

    // UTF-8 BOM prefix (\uFEFF) ensures Excel opens special characters and symbols correctly
    const csvContent = '\uFEFF' + [headers, ...rows].join('\r\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    const cleanName = masterName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.setAttribute('href', url);
    link.setAttribute('download', `TML_${cleanName}_export_${timestampStr}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Export to styled Excel spreadsheet (.xls / HTML Table format compliant with Excel)
   */
  exportToExcel: (options: MasterExportOptions) => {
    const { masterName, category, buFilter, currentUser, columns, data } = options;
    const now = new Date();
    const timestampStr = now.toISOString().slice(0, 10);
    const timeFormatted = now.toLocaleString('en-IN');

    const headerCells = columns
      .map(
        (col) =>
          `<th style="background-color: #002B49; color: #FFFFFF; font-weight: bold; padding: 10px; border: 1px solid #CBD5E1; text-align: left;">${col.label}</th>`
      )
      .join('');

    const dataRows = data
      .map((row, idx) => {
        const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
        const cells = columns
          .map((col) => {
            const val = row[col.key];
            const text = val !== undefined && val !== null ? String(val) : '';
            return `<td style="padding: 8px; border: 1px solid #E2E8F0; background-color: ${bg};">${text}</td>`;
          })
          .join('');
        return `<tr>${cells}</tr>`;
      })
      .join('');

    const excelHtml = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <!--[if gte mso 9]>
        <xml>
          <x:ExcelWorkbook>
            <x:ExcelWorksheets>
              <x:ExcelWorksheet>
                <x:Name>${masterName.slice(0, 31)}</x:Name>
                <x:WorksheetOptions>
                  <x:DisplayGridlines/>
                </x:WorksheetOptions>
              </x:ExcelWorksheet>
            </x:ExcelWorksheets>
          </x:ExcelWorkbook>
        </xml>
        <![endif]-->
        <meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">
      </head>
      <body>
        <table style="font-family: Calibri, Arial, sans-serif; font-size: 11pt; border-collapse: collapse;">
          <tr>
            <td colspan="${columns.length}" style="font-size: 16pt; font-weight: bold; color: #002B49; padding: 12px 0;">
              Tata Motors Service Transformation — ${masterName}
            </td>
          </tr>
          <tr>
            <td colspan="${columns.length}" style="color: #64748B; font-size: 10pt; padding-bottom: 8px;">
              Category: <b>${category || 'Enterprise Masters'}</b> | BU Filter: <b>${buFilter || 'All'}</b> | Generated by: <b>${currentUser ? `${currentUser.name} (${currentUser.userId})` : 'System Administrator'}</b> | Generated on: <b>${timeFormatted}</b> | Records: <b>${data.length}</b>
            </td>
          </tr>
          <thead>
            <tr>${headerCells}</tr>
          </thead>
          <tbody>
            ${dataRows}
          </tbody>
        </table>
      </body>
      </html>
    `;

    const blob = new Blob([excelHtml], { type: 'application/vnd.ms-excel;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    const cleanName = masterName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.setAttribute('href', url);
    link.setAttribute('download', `TML_${cleanName}_export_${timestampStr}.xls`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },
};
